# Generated by Django 3.1.3 on 2020-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='Modelo',
            field=models.CharField(choices=[('SVM', 'SoporteVectorial'), ('RF', 'BosquesAleatorios')], default=('SVM', 'SoporteVectorial'), max_length=100),
        ),
    ]
