---
title: "Descriptiva"
author: "Ana Gaona"
date: "9/11/2020"
output: html_document
---
```{r}
library("plotly")
library("ggplot2")
library("tidyr")
library("readr")
library("tibble")
library("dplyr") 
library("tidyverse")
library("gridExtra")

```

```{r}
datos <- read.csv("../datos_proscesados.csv")
```

# vISTA DE LOS DATOS
```{r}
datos$BARRIO <- as.factor(as.character(datos$BARRIO))
datos$COMUNA <- as.factor(as.character(datos$COMUNA))
#datos$GRAVEDAD <- as.factor(as.character(datos$GRAVEDAD))
datos$TIPO_GEOCOD <- as.factor(as.character(datos$TIPO_GEOCOD))
datos$DIA_NOMBRE <- as.factor(as.character(datos$DIA_NOMBRE))
datos$MES_NOMBRE <- as.factor(as.character(datos$MES_NOMBRE))
datos$DISENO <- as.factor(as.character(datos$DISENO))
datos$AUX_B <- as.factor(as.character(datos$AUX_B))
datos$AUX_C <- as.factor(as.character(datos$AUX_C))
datos$DIRECCION_ENC <- as.factor(as.character(datos$DIRECCION_ENC))
datos$DIRECCION <- as.factor(as.character(datos$DIRECCION))
datos$HORA <- as.factor(as.character(datos$HORA))
datos$FECHA <- as.factor(as.character(datos$FECHA))
datos$GRAVEDAD <- as.character(as.factor(datos$GRAVEDAD))
summary(datos)
```
# ANÁLISIS GRÁFICO DE LA ACCIDENTALIDAD:


```{r}
datos%>%ggplot(aes(y=GRAVEDAD, x=DIA_NOMBRE, fill=GRAVEDAD))+geom_bar(stat = "identity")
```
```{r}
datos%>%ggplot(aes(y=CLASE, x=DIA_NOMBRE, fill=CLASE))+geom_bar(stat = "identity")

```  
```{r}
datos%>%ggplot(aes(y=CLASE, x=MES_NOMBRE, fill=CLASE))+geom_bar(stat = "identity")

```  
```{r}
datos%>%ggplot(aes(y=GRAVEDAD, x=MES_NOMBRE, fill=GRAVEDAD))+geom_bar(stat = "identity")

```

```{r}
a<-datos%>%ggplot(aes(x=CLASE))+geom_histogram(alpha=.5,fill="dark blue")+geom_count(stat="count")

b<-datos%>%ggplot(aes(x=(GRAVEDAD),fill=DIA_NOMBRE))+geom_density(alpha=.5)+facet_wrap(~DIA_NOMBRE)+geom_count(stat="count")
plot(b)

C<-datos%>%ggplot(aes(x=(GRAVEDAD),fill=MES_NOMBRE))+geom_density(alpha=.5)+facet_wrap(~MES_NOMBRE)+geom_count(stat="count")
plot(C)


```
